# This is a basic workflow to help you get started with Actions

name: Generate Release

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the OpenCore branch
  push:
    branches: [OpenCore]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: build release file
        run: sh ./make.sh

      - name: list files
        run: ls -a

      - name: create release
        uses: jardenliu/create-release@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          code: latest
          name: Latest Release
          recreate: true
          body: >
            Latest auto release corresponding to commit ${{github.sha}} 🔥.
          assets: >
            XPS15-9560-i5-4K-OC.zip:i5-4K-OC.zip:application/zip
            XPS15-9560-i7-4K-OC.zip:i7-4K-OC.zip:application/zip
            XPS15-9560-i5-1080P-OC.zip:i5-1080P-OC.zip:application/zip XPS15-9560-i7-1080P-OC.zip:i7-1080P-OC.zip:application/zip
